# Generated by Django 4.2.16 on 2026-04-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScoreLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=200)),
                ("matched_title", models.CharField(max_length=200)),
                ("industry", models.CharField(max_length=50)),
                ("education_level", models.CharField(max_length=30)),
                ("years_experience", models.PositiveSmallIntegerField()),
                ("score", models.PositiveSmallIntegerField()),
                ("label", models.CharField(max_length=30)),
                ("factor_automation", models.PositiveSmallIntegerField()),
                ("factor_judgment", models.PositiveSmallIntegerField()),
                ("factor_industry", models.PositiveSmallIntegerField()),
                ("factor_sociotechnical", models.PositiveSmallIntegerField()),
                ("factor_adaptability", models.PositiveSmallIntegerField()),
                ("used_ai_profile", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["industry", "score"],
                        name="scoring_sco_industr_64e570_idx",
                    ),
                    models.Index(
                        fields=["matched_title", "score"],
                        name="scoring_sco_matched_e5655f_idx",
                    ),
                ],
            },
        ),
    ]
